backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/post
    label: "Posts" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Location", name: "location", widget: "string" }
          - { label: "Bio", name: "bio", widget: "text" }
          - label: "Bio Button Group"
            name: "biobuttons"
            widget: "list"
            summary: "{{fields.buttontitle}}"
            fields:
            - {label: "Button Title", name: "buttontitle", widget: "string"}
            - {label: "Button URL", name: "buttonurl", widget: "string"}
          - label: "Background"
            name: "background"
            widget: "object" 
            fields: 
            - { label: "Background Video", name: "bgvideo", widget: "file" }
            - { label: "Background Placeholder", name: "bgplaceholder", widget: "image"}
          - label: "Bio Links"
            name: "biolinks"
            widget: "list"
            summary: "{{fields.linktitle}}"
            fields: 
            - {label: "Link Title", name: "linktitle", widget: "string"}
            - {label: "Link URL", name: "linkurl", widget: "string"}
