backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Page Title", name: "page title", widget: "string" }
          - { label: "Page URL", name: "pageurl", widget: "string", required: false}
          - { label: "Nav Item", name: "navitem", widget: "boolean" }
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Location", name: "location", widget: "string" }
          - { label: "Bio", name: "bio", widget: "markdown" }
          - label: "Bio Button Group"
            name: "biobuttons"
            widget: "list"
            summary: "{{fields.buttontitle}}"
            fields:
            - { label: "Button Title", name: "buttontitle", widget: "string" }
            - { label: "Button URL", name: "buttonurl", widget: "string" }
          - label: "Background"
            name: "background"  
            widget: "object"  
            fields: 
            - { label: "Background Video", name: "bgvideo", widget: "file" }
            - { label: "Background Placeholder", name: "bgplaceholder", widget: "image" }
          - label: "Bio Links"
            name: "biolinks"
            widget: "list"
            summary: "{{fields.linktitle}}"
            fields: 
            - {label: "Link Title", name: "linktitle", widget: "string"}
            - {label: "Link URL", name: "linkurl", widget: "string"}
      - file: "content/images/_index.md"
        label: "Images"
        name: "images"
        fields:
          - { label: "Page Title", name: "pagetitle", widget: "string" }
          - { label: "Page URL", name: "pageurl", widget: "string" }
          - { label: "Nav Item", name: "navitem", widget: "boolean" }
          - label: "Image Projects"
            name: "imageprojects"
            widget: "list"
            summary: "{{fields.projecttitle}}"
            fields:
            - { label: "Project Title", name: "projecttitle", widget: "string"}
            - label: "Images"
              name: "images"
              widget: "list"
              summary: "{{fields.caption}}"
              fields: 
              - {label: "Caption", name: "caption", widget: "string"}
              - {label: "Image File", name: "imagefile", widget: "image"}
